apiVersion: apps/v1
kind: Deployment
metadata:
  name: verifier-deployment
  labels:
    app: fake-news-verifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-news-verifier
  template:
    metadata:
      labels:
        app: fake-news-verifier
    spec:
      containers:
        - name: verifier
          image: fake-news-verifier:phase2
          imagePullPolicy: Never
          command: ["python", "src/main.py"]
          args:
            - "--input"
            - "Breaking: 7.2 magnitude earthquake hits Nashville today!"
          # env:
          #   - name: SOME_VAR
          #     value: "value"
