apiVersion: v1
kind: Service
metadata:
  name: verifier-service
  labels:
    app: fake-news-verifier
spec:
  selector:
    app: fake-news-verifier
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
